Config = {}
Config.DrawDistance = 100
Config.MarkerSize = {x = 1.1, y = 1.1, z = 0.9}
Config.MarkerType =  21
Config.MarkerColor = {r = 102, g = 102, b = 204, a = 255}
Config.Locale = 'en'

Config.Zones = {

	LegionSquare = {
		Items = {
			{ name = "water", label = "Water", price = 10 },
			{ name = "adios", label = "Adios", price = 10 },
			{ name = "americano", label = "Americano", price = 10 },
			{ name = "bacardi", label = "Bacardi", price = 100 },
			{ name = "beer", label = "Beer", price = 100 },
			{ name = "cappuccino", label = "Cappuccino", price = 10 },
			{ name = "champagne", label = "Champagne", price = 10 },
			{ name = "cocacola", label = "Coca Cola", price = 10 },
			{ name = "coffee", label = "Coffee", price = 10 },
			{ name = "cosmopolitan", label = "Cosmopolitan", price = 10 },
			{ name = "cubalibre", label = "Cubalibre", price = 10 },
			{ name = "drink_meloun", label = "Watermelon Drink", price = 10 },
			{ name = "drpepper", label = "Dr Pepper", price = 10 },
			{ name = "energy", label = "Monster", price = 10 },
			{ name = "espresso", label = "Espresso", price = 10 },
			{ name = "espresso_latte", label = "Espresso Latte", price = 10 },
			{ name = "frappe", label = "Frappe", price = 10 },
			{ name = "frappucino", label = "Frappucino", price = 10 },
			{ name = "golem", label = "Golem", price = 100 },
			{ name = "icetea", label = "Ice Tea", price = 10 },
			{ name = "jager", label = "Jager", price = 100 },
			{ name = "jagerbomb", label = "Jager Bomb", price = 100 },
			{ name = "jahoda_smoot", label = "Jahoda Smooth", price = 10 },
			{ name = "jus_raisin", label = "Grape Juice", price = 10 },
			{ name = "jusfruit", label = "Fruit Juice", price = 10 },
			{ name = "limonade", label = "Lemonade", price = 10 },
			{ name = "logger", label = "Logger", price = 100 },
			{ name = "longisland", label = "Long Island", price = 100 },
			{ name = "martini", label = "Martini", price = 100 },
			{ name = "manhattan", label = "Manhattan", price = 100 },
			{ name = "pinacolada", label = "Pinacolada", price = 100 },
			{ name = "pineapple_drink", label = "Pineapple Drink", price = 10 },
			{ name = "purifiedwater", label = "Purified Water", price = 20 },
			{ name = "redbull", label = "RedBull", price = 10 },
			{ name = "rhum", label = "Rhum", price = 100 },
			{ name = "vodka", label = "Vodka", price = 100 },
			{ name = "wine", label = "Wine", price = 100 },

			{ name = "activia", label = "Activia", price = 10 },
			{ name = "baconfries", label = "Bacon & Fries", price = 10 },
			{ name = "bagel", label = "Bagel", price = 10 },
			{ name = "ban_muffin", label = "Banana Muffin", price = 10 },
			{ name = "banana", label = "Banana", price = 10 },
			{ name = "bolchips", label = "Bag Of Chips", price = 10 },
			{ name = "blue_muffin", label = "Blueberry Muffin", price = 10 },
			{ name = "bread", label = "Bread", price = 10 },
			{ name = "caesar", label = "Caesar Salad", price = 10 },
			{ name = "calzone", label = "Calzone", price = 10 },
			{ name = "chocolate", label = "Chocolate", price = 10 },
			{ name = "chocolates", label = "Box Of Chocolate", price = 10 },
			{ name = "croissant", label = "Croissant", price = 10 },
			{ name = "cupcake", label = "Cupcake", price = 10 },
			{ name = "donut", label = "Donut", price = 10 },
			{ name = "fries", label = "Fries", price = 10 },
			{ name = "burger", label = "Burger", price = 10 },
			{ name = "steak", label = "Steak", price = 10 },
			{ name = "hamburger", label = "Hamburger", price = 10 },
			{ name = "klobasa", label = "Klobasa", price = 10 },
			{ name = "lasagne", label = "Lasagne", price = 10 },
			{ name = "nachos_salsa", label = "Nachos Salsa", price = 10 },
			{ name = "nachos_syr", label = "Nachos", price = 10 },
			{ name = "packaged_chicken", label = "Packaged Chicken", price = 10 },
			{ name = "pancake", label = "Pancake", price = 10 },
			{ name = "pizza", label = "Pizza", price = 10 },
			{ name = "popcorn", label = "Popcorn", price = 10 },
			{ name = "popcorn_karamel", label = "Popcorn Karamel", price = 10 },
			{ name = "pretcil", label = "Pretcil", price = 10 },
			{ name = "proteinbar", label = "Protein Bar", price = 10 },
			{ name = "sandwich", label = "Sandwich", price = 10 },
			{ name = "saucisson", label = "Sausage", price = 10 },
			{ name = "spagetie", label = "Spagetie", price = 10 },
			{ name = "tortellini", label = "Tortellini", price = 10 },
			{ name = "yogurt", label = "Yogurt", price = 10 }
		},
		Pos = {
			vector3(190.08, -889.44, 30.71)
		},
		Size  = 1.0,
		Type  = 59,
		Color = 25,
		ShowBlip = true,
		ShowMarker = true
	},

	TwentyFourSeven = {
		Items = {
			{ name = "water", label = "Water", price = 10 },
			{ name = "adios", label = "Adios", price = 10 },
			{ name = "americano", label = "Americano", price = 10 },
			{ name = "bacardi", label = "Bacardi", price = 100 },
			{ name = "beer", label = "Beer", price = 100 },
			{ name = "cappuccino", label = "Cappuccino", price = 10 },
			{ name = "champagne", label = "Champagne", price = 10 },
			{ name = "cocacola", label = "Coca Cola", price = 10 },
			{ name = "coffee", label = "Coffee", price = 10 },
			{ name = "cosmopolitan", label = "Cosmopolitan", price = 10 },
			{ name = "cubalibre", label = "Cubalibre", price = 10 },
			{ name = "drink_meloun", label = "Watermelon Drink", price = 10 },
			{ name = "drpepper", label = "Dr Pepper", price = 10 },
			{ name = "energy", label = "Monster", price = 10 },
			{ name = "espresso", label = "Espresso", price = 10 },
			{ name = "espresso_latte", label = "Espresso Latte", price = 10 },
			{ name = "frappe", label = "Frappe", price = 10 },
			{ name = "frappucino", label = "Frappucino", price = 10 },
			{ name = "golem", label = "Golem", price = 100 },
			{ name = "icetea", label = "Ice Tea", price = 10 },
			{ name = "jager", label = "Jager", price = 100 },
			{ name = "jagerbomb", label = "Jager Bomb", price = 100 },
			{ name = "jahoda_smoot", label = "Jahoda Smooth", price = 10 },
			{ name = "jus_raisin", label = "Grape Juice", price = 10 },
			{ name = "jusfruit", label = "Fruit Juice", price = 10 },
			{ name = "limonade", label = "Lemonade", price = 10 },
			{ name = "logger", label = "Logger", price = 100 },
			{ name = "longisland", label = "Long Island", price = 100 },
			{ name = "martini", label = "Martini", price = 100 },
			{ name = "manhattan", label = "Manhattan", price = 100 },
			{ name = "pinacolada", label = "Pinacolada", price = 100 },
			{ name = "pineapple_drink", label = "Pineapple Drink", price = 10 },
			{ name = "purifiedwater", label = "Purified Water", price = 20 },
			{ name = "redbull", label = "RedBull", price = 10 },
			{ name = "rhum", label = "Rhum", price = 100 },
			{ name = "vodka", label = "Vodka", price = 100 },
			{ name = "wine", label = "Wine", price = 100 },

			{ name = "activia", label = "Activia", price = 10 },
			{ name = "baconfries", label = "Bacon & Fries", price = 10 },
			{ name = "bagel", label = "Bagel", price = 10 },
			{ name = "ban_muffin", label = "Banana Muffin", price = 10 },
			{ name = "banana", label = "Banana", price = 10 },
			{ name = "bolchips", label = "Bag Of Chips", price = 10 },
			{ name = "blue_muffin", label = "Blueberry Muffin", price = 10 },
			{ name = "bread", label = "Bread", price = 10 },
			{ name = "caesar", label = "Caesar Salad", price = 10 },
			{ name = "calzone", label = "Calzone", price = 10 },
			{ name = "chocolate", label = "Chocolate", price = 10 },
			{ name = "chocolates", label = "Box Of Chocolate", price = 10 },
			{ name = "croissant", label = "Croissant", price = 10 },
			{ name = "cupcake", label = "Cupcake", price = 10 },
			{ name = "donut", label = "Donut", price = 10 },
			{ name = "fries", label = "Fries", price = 10 },
			{ name = "burger", label = "Burger", price = 10 },
			{ name = "steak", label = "Steak", price = 10 },
			{ name = "hamburger", label = "Hamburger", price = 10 },
			{ name = "klobasa", label = "Klobasa", price = 10 },
			{ name = "lasagne", label = "Lasagne", price = 10 },
			{ name = "nachos_salsa", label = "Nachos Salsa", price = 10 },
			{ name = "nachos_syr", label = "Nachos", price = 10 },
			{ name = "packaged_chicken", label = "Packaged Chicken", price = 10 },
			{ name = "pancake", label = "Pancake", price = 10 },
			{ name = "pizza", label = "Pizza", price = 10 },
			{ name = "popcorn", label = "Popcorn", price = 10 },
			{ name = "popcorn_karamel", label = "Popcorn Karamel", price = 10 },
			{ name = "pretcil", label = "Pretcil", price = 10 },
			{ name = "proteinbar", label = "Protein Bar", price = 10 },
			{ name = "sandwich", label = "Sandwich", price = 10 },
			{ name = "saucisson", label = "Sausage", price = 10 },
			{ name = "spagetie", label = "Spagetie", price = 10 },
			{ name = "tortellini", label = "Tortellini", price = 10 },
			{ name = "yogurt", label = "Yogurt", price = 10 }
		},
		Pos = {
			vector3(373.8, 325.8, 102.5),
			vector3(2557.4, 382.2, 107.6),
			vector3(-3038.9, 585.9, 6.9),
			vector3(-3241.9, 1001.4, 11.8),
			vector3(547.4, 2671.7, 41.1),
			vector3(1961.4, 3740.6, 31.3),
			vector3(2678.9, 3280.6, 54.2),
			vector3(1729.2, 6414.1, 34.0)
		},
		Size  = 1.0,
		Type  = 59,
		Color = 25,
		ShowBlip = true,
		ShowMarker = true
	},

	RobsLiquor = {
		Items = {
			{ name = "water", label = "Water", price = 10 },
			{ name = "americano", label = "Americano", price = 100 },
			{ name = "beer", label = "Beer", price = 100 },
			{ name = "champagne", label = "Champagne", price = 100 },
			{ name = "cosmopolitan", label = "Cosmopolitan", price = 100 },
			{ name = "cubalibre", label = "Cubalibre", price = 100 },
			{ name = "drink_meloun", label = "Watermelon Drink", price = 100 },
			{ name = "golem", label = "Golem", price = 100 },
			{ name = "jager", label = "Jager", price = 100 },
			{ name = "jagerbomb", label = "Jager Bomb", price = 100 },
			{ name = "logger", label = "Logger", price = 100 },
			{ name = "longisland", label = "Long Island", price = 100 },
			{ name = "martini", label = "Martini", price = 100 },
			{ name = "manhattan", label = "Manhattan", price = 100 },
			{ name = "pinacolada", label = "Pinacolada", price = 100 },
			{ name = "pineapple_drink", label = "Pineapple Drink", price = 100 },
			{ name = "purifiedwater", label = "Purified Water", price = 20 },
			{ name = "redbull", label = "RedBull", price = 10 },
			{ name = "rhum", label = "Rhum", price = 100 },
			{ name = "vodka", label = "Vodka", price = 100 },
			{ name = "wine", label = "Wine", price = 100 }
		},
		Pos = {
			vector3(1135.8, -982.2, 45.4),
			vector3(-1222.9, -906.9, 11.3),
			vector3(-1487.5, -379.1, 39.1),
			vector3(-2968.2, 390.9, 14.0),
			vector3(1166.0, 2708.9, 37.1),
			vector3(1392.5, 3604.6,  33.9),
			vector3(127.8,  -1284.7, 28.2), --StripClub
			vector3(-1393.4, -606.6, 29.3), --Tequila la
			vector3(-559.9, 287.0, 81.1) --Bahamamas
		},
		Size  = 1.0,
		Type  = 59,
		Color = 25,
		ShowBlip = true,
		ShowMarker = true
	},

	LTDgasoline = {
		Items = {
			{ name = "water", label = "Water", price = 10 },
			{ name = "adios", label = "Adios", price = 10 },
			{ name = "americano", label = "Americano", price = 10 },
			{ name = "bacardi", label = "Bacardi", price = 100 },
			{ name = "beer", label = "Beer", price = 100 },
			{ name = "cappuccino", label = "Cappuccino", price = 10 },
			{ name = "champagne", label = "Champagne", price = 10 },
			{ name = "cocacola", label = "Coca Cola", price = 10 },
			{ name = "coffee", label = "Coffee", price = 10 },
			{ name = "cosmopolitan", label = "Cosmopolitan", price = 10 },
			{ name = "cubalibre", label = "Cubalibre", price = 10 },
			{ name = "drink_meloun", label = "Watermelon Drink", price = 10 },
			{ name = "drpepper", label = "Dr Pepper", price = 10 },
			{ name = "energy", label = "Monster", price = 10 },
			{ name = "espresso", label = "Espresso", price = 10 },
			{ name = "espresso_latte", label = "Espresso Latte", price = 10 },
			{ name = "frappe", label = "Frappe", price = 10 },
			{ name = "frappucino", label = "Frappucino", price = 10 },
			{ name = "golem", label = "Golem", price = 100 },
			{ name = "icetea", label = "Ice Tea", price = 10 },
			{ name = "jager", label = "Jager", price = 100 },
			{ name = "jagerbomb", label = "Jager Bomb", price = 100 },
			{ name = "jahoda_smoot", label = "Jahoda Smooth", price = 10 },
			{ name = "jus_raisin", label = "Grape Juice", price = 10 },
			{ name = "jusfruit", label = "Fruit Juice", price = 10 },
			{ name = "limonade", label = "Lemonade", price = 10 },
			{ name = "logger", label = "Logger", price = 100 },
			{ name = "longisland", label = "Long Island", price = 100 },
			{ name = "martini", label = "Martini", price = 100 },
			{ name = "manhattan", label = "Manhattan", price = 100 },
			{ name = "pinacolada", label = "Pinacolada", price = 100 },
			{ name = "pineapple_drink", label = "Pineapple Drink", price = 10 },
			{ name = "purifiedwater", label = "Purified Water", price = 20 },
			{ name = "redbull", label = "RedBull", price = 10 },
			{ name = "rhum", label = "Rhum", price = 100 },
			{ name = "vodka", label = "Vodka", price = 100 },
			{ name = "wine", label = "Wine", price = 100 },

			{ name = "activia", label = "Activia", price = 10 },
			{ name = "baconfries", label = "Bacon & Fries", price = 10 },
			{ name = "bagel", label = "Bagel", price = 10 },
			{ name = "ban_muffin", label = "Banana Muffin", price = 10 },
			{ name = "banana", label = "Banana", price = 10 },
			{ name = "bolchips", label = "Bag Of Chips", price = 10 },
			{ name = "blue_muffin", label = "Blueberry Muffin", price = 10 },
			{ name = "bread", label = "Bread", price = 10 },
			{ name = "caesar", label = "Caesar Salad", price = 10 },
			{ name = "calzone", label = "Calzone", price = 10 },
			{ name = "chocolate", label = "Chocolate", price = 10 },
			{ name = "chocolates", label = "Box Of Chocolate", price = 10 },
			{ name = "croissant", label = "Croissant", price = 10 },
			{ name = "cupcake", label = "Cupcake", price = 10 },
			{ name = "donut", label = "Donut", price = 10 },
			{ name = "fries", label = "Fries", price = 10 },
			{ name = "burger", label = "Burger", price = 10 },
			{ name = "steak", label = "Steak", price = 10 },
			{ name = "hamburger", label = "Hamburger", price = 10 },
			{ name = "klobasa", label = "Klobasa", price = 10 },
			{ name = "lasagne", label = "Lasagne", price = 10 },
			{ name = "nachos_salsa", label = "Nachos Salsa", price = 10 },
			{ name = "nachos_syr", label = "Nachos", price = 10 },
			{ name = "packaged_chicken", label = "Packaged Chicken", price = 10 },
			{ name = "pancake", label = "Pancake", price = 10 },
			{ name = "pizza", label = "Pizza", price = 10 },
			{ name = "popcorn", label = "Popcorn", price = 10 },
			{ name = "popcorn_karamel", label = "Popcorn Karamel", price = 10 },
			{ name = "pretcil", label = "Pretcil", price = 10 },
			{ name = "proteinbar", label = "Protein Bar", price = 10 },
			{ name = "sandwich", label = "Sandwich", price = 10 },
			{ name = "saucisson", label = "Sausage", price = 10 },
			{ name = "spagetie", label = "Spagetie", price = 10 },
			{ name = "tortellini", label = "Tortellini", price = 10 },
			{ name = "yogurt", label = "Yogurt", price = 10 }
		},
		Pos = {
			vector3(-48.5,  -1757.5, 28.4),
			vector3(1163.3, -323.8, 68.2),
			vector3(-707.5, -914.2, 18.2),
			vector3(-1820.5, 792.5, 137.1),
			vector3(1698.3, 4924.4, 41.0)
		},
		Size  = 1.0,
		Type  = 59,
		Color = 25,
		ShowBlip = true,
		ShowMarker = true
	}
}
