$engine: 3
$onesync: legacy
name: OPRPESX
version: 0.0.1
author: Jay
description: ESX for Ontario Provincial RolePlay 

tasks:
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[cfx-default]
  
  # Download and prepare server.cfg / database / default scripts
  - action: download_github
    src: https://github.com/JayPaulinCodes/OPRP-ESX-RECIPE
    ref: master
    dest: ./tmp/oprp_esx

  - action: move_path
    src: ./tmp/oprp_esx/server.cfg
    dest: ./server.cfg

  - action: move_path
    src: ./tmp/oprp_esx/server/configs
    dest: ./configs

  - action: move_path
    src: ./tmp/oprp_esx/server/resources/[legacy]
    dest: ./resources/[legacy]

  - action: move_path
    src: ./tmp/oprp_esx/server/resources/[Scripts]
    dest: ./resources/[Scripts]

  - action: connect_database
  - action: query_database
    file: ./tmp/oprp_esx/oprp.sql

  # Download basic resources and ESX dependencies
  # - action: download_github
  #   src: https://github.com/esx-framework/esx-legacy
  #   ref: 8153f6a9221baeef0affb0176e5811007b8f5e3b
  #   dest: ./resources/[legacy]

  - action: download_github
    src: https://github.com/Bob74/bob74_ipl
    ref: e949c08c67bdfe3fb981bf4f77477faf26d187e6
    dest: ./resources/bob74_ipl
  
  - action: download_github
    src: https://github.com/brouznouf/fivem-mysql-async
    ref: c5fa317a65acfe2eef453257e19e3b4fde137089
    dest: ./resources/mysql-async

  - action: download_github
    src: https://github.com/DevTestingPizza/vSync
    ref: 65f0e3cdd5692b619985a7df6297ffca7db41525
    dest: ./tmp/vSync

  - action: move_path
    src: ./tmp/vSync/vSync
    dest: ./resources/vSync

  ## GCPhone stuff
  - action: download_file
    url: https://github.com/Re-Ignited-Development/Re-Ignited-Phone/releases/download/V1.5/resources-1.2.zip
    path: ./tmp/gcphone.zip
  - action: unzip
    src: ./tmp/gcphone.zip
    dest: ./tmp
  - action: move_path
    src: ./tmp/resources-1.2/gcphone
    dest: ./resources/gcphone

  ## Downloading & Patching configs: cosmo hud
  - action: download_github
    src: https://github.com/nojdh/cosmo_hud
    ref: eed8fd7b8cbe8a02ae7339d4dee05b5d56a8097c
    subpath: cosmo_hud
    dest: ./resources/[hud]/cosmo_hud

  # - action: replace_string
  #   file: ./resources/[legacy]/[esx_addons]/esx_status/config.lua
  #   search: "    Config.Display        = true"
  #   replace: "    Config.Display        = false"

  - action: replace_string
    file: ./resources/[hud]/cosmo_hud/config.lua
    search: 'Config.AlwaysShowRadar = false'
    replace: 'Config.AlwaysShowRadar = true'

  # ## Patching configs: esx_basicneeds
  # - action: replace_string
  #   file: ./resources/[legacy]/[esx_addons]/esx_basicneeds/config.lua
  #   search: 'Config.Visible = true'
  #   replace: 'Config.Visible = false'

  ## Patching configs: multicharacter 
  - action: replace_string
    file: ./resources/[legacy]/[esx]/es_extended/config.lua
    search: 'Config.Multichar                = false'
    replace: 'Config.Multichar = true '

  - action: replace_string
    file: ./resources/[legacy]/[esx_addons]/esx_multicharacter/server/main.lua
    search: "Config.Database = 'es_extended'"
    replace: "Config.Database = '{{dbName}}'"

  - action: replace_string
    mode: all_vars
    file: 
    # - ./resources/loadingscreen/config.js
    - ./resources/[legacy]/[esx_addons]/esx_multicharacter/server/main.lua

  
  ## Cleanup
  - action: remove_path
    path: ./tmp
  - action: remove_path
    path: ./resources/server.cfg
  - action: remove_path
    path: ./resources/[legacy]/[esx_addons]/esx_whitelist
  - action: remove_path
    path: ./resources/[legacy]/[esx_addons]/esx_voice
  - action: remove_path
    path: ./resources/[legacy]/[esx_addons]/esx_phone