	(1   , '2006 Impala'                       , 'impalal'        , 500    , 'chevrolet'      , '' ),
	(2   , '2015 Camaro'                       , 'z28'            , 500    , 'chevrolet'      , '' ),
	(3   , '2016 Challenger'                   , '16challenger'   , 500    , 'dodge'          , '' ),
	(4   , '2016 Charger'                      , '16charger'      , 500    , 'dodge'          , '' ),
	(5   , '2017 GTR'                          , '17r35'          , 500    , 'nissan'         , '' ),
	(6   , '2017 RV'                           , '17jamb'         , 500    , 'ford'           , '' ),
	(7   , '1969 Charger'                      , 'charger69'      , 500    , 'dodge'          , '' ),
	(8   , '2019 Mustang GT'                   , 'mustang19'      , 500    , 'ford'           , '' ),
	(9   , '2011 Retired CVPI'                 , 'crownvic'       , 500    , 'ford'           , '' ),
	(10  , '2012 Rubicon'                      , 'jp12'           , 500    , 'jeep'           , '' ),
	(11  , '2012 Ranger'                       , 'bcranger'       , 500    , 'ford'           , '' ),
	(12  , '2013 i30'                          , 'bmhyundaii30'   , 500    , 'hyundai'        , '' ),
	(13  , '2016 Suburban'                     , 'subn'           , 500    , 'chevrolet'      , '' ),
	(14  , '2017 F-150 Hennessey Velociraptor' , 'velociraptor'   , 500    , 'ford'           , '' ),
	(15  , '2020 Sierra Denali HD 3500'        , '20denalihd'     , 500    , 'gmc'            , '' ),
	(16  , '2018 Camaro'                       , 'alpha6'         , 500    , 'chevrolet'      , '' ),
	(17  , '2018 3500 Flatbed'                 , '3500flatbed'    , 500    , 'ram'            , '' ),
	(18  , '2003 350Z'                         , 'dk350z'         , 500    , 'nissan'         , '' ),
	(19  , '2021 5008'                         , '50082021civ'    , 500    , 'peugeot'        , '' ),
	(20  , '1995 Bel Air'                      , 'onefifty55'     , 500    , 'chevrolet'      , '' ),
	(21  , '1966 Nova'                         , 'nova'           , 500    , 'chevrolet'      , '' ),
	(22  , '1969 Mustang Boss 302'             , 'boss302'        , 500    , 'ford'           , '' ),
	(23  , '1970 Challenger'                   , 'chall70'        , 500    , 'dodge'          , '' ),
	(24  , '1988 Monte Carlo'                  , 'montecarlo'     , 500    , 'chevrolet'      , '' ),
	(25  , '1999 Civic'                        , 'civic'          , 500    , 'honda'          , '' ),
	(26  , 'CAA Truck'                         , '4b'             , 500    , 'other'          , '' ),
	(27  , '2015 Alpina B7'                    , 'b7l06'          , 500    , 'bmw'            , '' ),
	(28  , '2008 S4'                           , 'b5s4'           , 500    , 'audi'           , '' ),
	(29  , '2015 TTRS'                         , 'ttrs'           , 500    , 'audi'           , '' ),
	(30  , '2019 R8'                           , 'lbr8'           , 500    , 'audi'           , '' ),
	(31  , '2021 Bentayga'                     , 'huntley'        , 500    , 'bently'         , '' ),
	(32  , '2010 Mulsanne'                     , 'bmm'            , 500    , 'bently'         , '' ),
	(33  , '2022 7'                            , '750li'          , 500    , 'bmw'            , '' ),
	(34  , '2020 M5'                           , 'm5f90'          , 500    , 'bmw'            , '' ),
	(35  , '2018 M6'                           , 'm6f13'          , 500    , 'bmw'            , '' ),
	(36  , '2018 X5'                           , 'x5e53'          , 500    , 'bmw'            , '' ),
	(37  , '2018 X6M'                          , 'x6m'            , 500    , 'bmw'            , '' ),
	(38  , '2018 M5 F90'                       , 'bmci'           , 500    , 'bmw'            , '' ),
	(39  , '1980 Bronco'                       , 'bronco'         , 500    , 'ford'           , '' ),
	(40  , '2013 BRZ'                          , 'brz13'          , 500    , 'subaru'         , '' ),
	(41  , '2020 Chiron'                       , 'chiron'         , 500    , 'bugatti'        , '' ),
	(42  , '1970 GSX'                          , 'gsxb'           , 500    , 'buick'          , '' ),
	(43  , '1987 GNX'                          , 'bgnx'           , 500    , 'buick'          , '' ),
	(44  , '2021 C-HR Hybrid'                  , 'chr'            , 500    , 'toyota'         , '' ),
	(45  , '2019 Corvette'                     , 'c7'             , 500    , 'chevrolet'      , '' ),
	(46  , '2012 Escalade GMT900'              , 'gmt900escalade' , 500    , 'cadillac'       , '' ),
	(47  , '2010 CTS Sports Wagon'             , 'ctssw10'        , 500    , 'cadillac'       , '' ),
	(48  , '2018 Camry'                        , 'camry18 '       , 500    , 'toyota'         , '' ),
	(49  , 'Canada Post Van'                   , 'boxville2'      , 500    , 'other'          , '' ),
	(50  , 'Garbage Truck'                     , 'trash'          , 500    , 'other'          , '' ),
	(51  , '2013 Caprice'                      , 'caprice13'      , 500    , 'chevrolet'      , '' ),
	(52  , '2018 Caravan'                      , 'minivan'        , 500    , 'dodge'          , '' ),
	(53  , 'Cat Truck'                         , 'ct660'          , 500    , 'other'          , '' ),
	(54  , '2016 Tahoe'                        , 'tahoe'          , 500    , 'chevrolet'      , '' ),
	(55  , '2015 Explorer'                     , 'explorer'       , 500    , 'ford'           , '' ),
	(56  , 'Liebherr Excavator'                , 'excabator'      , 500    , 'other'          , '' ),
	(57  , '2018 F-350'                        , '18f350ds'       , 500    , 'ford'           , '' ),
	(58  , '1978 F-150'                        , 'f15078'         , 500    , 'ford'           , '' ),
	(59  , '2019 F-350'                        , 'f35019'         , 500    , 'ford'           , '' ),
	(60  , '2018 Fusion'                       , 'fusion18'       , 500    , 'ford'           , '' ),
	(61  , '2020 AMG G 63'                     , 'gxg63'          , 500    , 'mercedes'       , '' ),
	(62  , 'GoKart'                            , 'gokart'         , 500    , 'other'          , '' ),
	(63  , 'GoKart Trailer'                    , 'ctrailer'       , 500    , 'other'          , '' ),
	(64  , 'HDWrecker'                         , 'hdwrecker'      , 500    , 'other'          , '' ),
	(65  , '2010 Pickup'                       , 'h3'             , 500    , 'hummer'         , '' ),
	(66  , 'Ice Cream Truck'                   , 'boxville'       , 500    , 'other'          , '' ),
	(67  , '2021 Odyssey'                      , 'honody'         , 500    , 'honda'          , '' ),
	(68  , 'Flat Trailer'                      , 'trflat'         , 500    , 'other'          , '' ),
	(69  , 'Small Trailer'                     , 'trailersmall'   , 500    , 'other'          , '' ),
	(70  , '2022 Z'                            , 'protoz'         , 500    , 'nissan'         , '' ),
	(71  , '2019 1500'                         , 'ram1500'        , 500    , 'ram'            , '' ),
	(72  , '2021 Velar'                        , 'velar'          , 500    , 'rangerover'     , '' ),
	(73  , 'Snowplow'                          , 'rapsnow'        , 500    , 'other'          , '' ),
	(74  , 'School Bus'                        , 'pbus2'          , 500    , 'other'          , '' ),
	(75  , '2019 Sorento'                      , 'sorento19'      , 500    , 'kia'            , '' ),
	(76  , '2012 F-350 Superduty'              , 'superduty'      , 500    , 'ford'           , '' ),
	(77  , '2021 Tahoe'                        , 'tahoe21'        , 500    , 'chevrolet'      , '' ),
	(78  , 'Taxi'                              , 'taxi'           , 500    , 'other'          , '' ),
	(79  , 'TTC Bus'                           , 'bus'            , 500    , 'other'          , '' ),
	(80  , '2001 Crown Victoria'               , 'cv98'           , 500    , 'ford'           , '' ),
	(81  , '1996 Plymouth Voyager'             , 'voyager96'      , 500    , 'chrysler'       , '' ),
	(82  , '2014 AMG S63 W222'                 , 's63w222'        , 500    , 'mercedes'       , '' ),
	(83  , '2017 AMG C63 S'                    , 'c63w205'        , 500    , 'mercedes'       , '' ),
	(84  , '1950 Pickup'                       , 'che1950ez'      , 500    , 'chevrolet'      , '' ),
	(85  , '1990 560sel W126'                  , '560sel'         , 500    , 'mercedes'       , '' ),
	(86  , 'Asbo'                              , 'asbo'           , 15000  , 'compacts'       , '' ),
	(2   , 'Blista'                            , 'blista'         , 15000  , 'compacts'       , '' ),
	(3   , 'Brioso R/A'                        , 'brioso'         , 17500  , 'compacts'       , '' ),
	(4   , 'Brioso 300'                        , 'brioso2'        , 12500  , 'compacts'       , '' ),
	(5   , 'Club'                              , 'club'           , 12500  , 'compacts'       , '' ),
	(6   , 'Dilettante'                        , 'dilettante'     , 15000  , 'compacts'       , '' ),
	(7   , 'Issi'                              , 'issi2'          , 15000  , 'compacts'       , '' ),
	(8   , 'Issi Classic'                      , 'issi3'          , 12500  , 'compacts'       , '' ),
	(9   , 'Kanjo Blista'                      , 'kanjo'          , 15000  , 'compacts'       , '' ),
	(10  , 'Panto'                             , 'panto'          , 15000  , 'compacts'       , '' ),
	(11  , 'Prairie'                           , 'prairie'        , 15000  , 'compacts'       , '' ),
	(12  , 'Rhapsody'                          , 'rhapsody'       , 12500  , 'compacts'       , '' ),
	(13  , 'WeEvil'                            , 'weevil'         , 12500  , 'compacts'       , '' ),
	(50  , 'Asea'                              , 'asea'           , 15000  , 'sedans'         , '' ),
	(51  , 'Asterope'                          , 'asterope'       , 15000  , 'sedans'         , '' ),
	(52  , 'Cognoscenti S'                     , 'cog55'          , 50000  , 'sedans'         , '' ),
	(53  , 'Cognoscenti S Armored'             , 'cog552'         , 75000  , 'sedans'         , '' ),
	(54  , 'Cognoscenti L'                     , 'cognoscenti'    , 50000  , 'sedans'         , '' ),
	(55  , 'Cognoscenti L Armored'             , 'cognoscenti2'   , 75000  , 'sedans'         , '' ),
	(56  , 'Emperor'                           , 'emperor'        , 12500  , 'sedans'         , '' ),
	(57  , 'Emperor 2'                         , 'emperor2'       , 10000  , 'sedans'         , '' ),
	(58  , 'Fugitive'                          , 'fugitive'       , 15000  , 'sedans'         , '' ),
	(59  , 'Glendale'                          , 'glendale'       , 12500  , 'sedans'         , '' ),
	(60  , 'Glendale Custom'                   , 'glendale2'      , 15000  , 'sedans'         , '' ),
	(61  , 'Ingot'                             , 'ingot'          , 12500  , 'sedans'         , '' ),
	(62  , 'Intruder'                          , 'intruder'       , 15000  , 'sedans'         , '' ),
	(63  , 'Premier'                           , 'premier'        , 15000  , 'sedans'         , '' ),
	(64  , 'Primo'                             , 'primo'          , 12500  , 'sedans'         , '' ),
	(65  , 'Primo Custom'                      , 'primo2'         , 15000  , 'sedans'         , '' ),
	(66  , 'Regina'                            , 'regina'         , 12500  , 'sedans'         , '' ),
	(67  , 'Romero Hearse'                     , 'romero'         , 15000  , 'sedans'         , '' ),
	(68  , 'Schafter'                          , 'schafter2'      , 15000  , 'sedans'         , '' ),
	(69  , 'Schafter V12 Armored'              , 'schafter5'      , 40000  , 'sedans'         , '' ),
	(70  , 'Schafter LWB Armored'              , 'schafter6'      , 40000  , 'sedans'         , '' ),
	(71  , 'Stafford'                          , 'stafford'       , 25000  , 'sedans'         , '' ),
	(72  , 'Stanier'                           , 'stanier'        , 12500  , 'sedans'         , '' ),
	(73  , 'Stratum'                           , 'stratum'        , 12500  , 'sedans'         , '' ),
	(74  , 'Stretch'                           , 'stretch'        , 50000  , 'sedans'         , '' ),
	(75  , 'Super Diamond'                     , 'superd'         , 50000  , 'sedans'         , '' ),
	(76  , 'Surge'                             , 'surge'          , 15000  , 'sedans'         , '' ),
	(77  , 'Tailgater'                         , 'tailgater'      , 15000  , 'sedans'         , '' ),
	(78  , 'Warrener'                          , 'warrener'       , 12500  , 'sedans'         , '' ),
	(79  , 'Washington'                        , 'washington'     , 12500  , 'sedans'         , '' ),
	(100 , 'Baller'                            , 'baller'         , 22500  , 'suvs'           , '' ),
	(101 , 'Baller 2'                          , 'baller2'        , 25000  , 'suvs'           , '' ),
	(102 , 'Baller LE'                         , 'baller3'        , 25000  , 'suvs'           , '' ),
	(103 , 'Baller LE LWB'                     , 'baller4'        , 25000  , 'suvs'           , '' ),
	(104 , 'Baller LE Armored'                 , 'baller5'        , 50000  , 'suvs'           , '' ),
	(105 , 'Baller LE LWB Armored'             , 'baller6'        , 50000  , 'suvs'           , '' ),
	(106 , 'BeeJay XL'                         , 'bjxl'           , 22500  , 'suvs'           , '' ),
	(107 , 'Cavalcade'                         , 'cavalcade'      , 22500  , 'suvs'           , '' ),
	(108 , 'Cavalcade 2'                       , 'cavalcade2'     , 25000  , 'suvs'           , '' ),
	(109 , 'Dubsta'                            , 'dubsta'         , 45000  , 'suvs'           , '' ),
	(110 , 'Dubsta Luxuary'                    , 'dubsta2'        , 45000  , 'suvs'           , '' ),
	(111 , 'Fhantom'                           , 'fq2'            , 22500  , 'suvs'           , '' ),
	(112 , 'Grabger'                           , 'granger'        , 22500  , 'suvs'           , '' ),
	(113 , 'Gresley'                           , 'gresley'        , 25000  , 'suvs'           , '' ),
	(114 , 'Habanero'                          , 'habanero'       , 22500  , 'suvs'           , '' ),
	(115 , 'Huntley S'                         , 'huntley'        , 25000  , 'suvs'           , '' ),
	(116 , 'Landstalker'                       , 'landstalker'    , 22500  , 'suvs'           , '' ),
	(117 , 'Landstalker XL'                    , 'landstalker2'   , 25000  , 'suvs'           , '' ),
	(118 , 'Mesa'                              , 'mesa'           , 22500  , 'suvs'           , '' ),
	(119 , 'Novak'                             , 'novak'          , 25000  , 'suvs'           , '' ),
	(120 , 'Patriot'                           , 'patriot'        , 25000  , 'suvs'           , '' ),
	(121 , 'Patriot Stretch'                   , 'patriot2'       , 45000  , 'suvs'           , '' ),
	(122 , 'Radius'                            , 'radi'           , 22500  , 'suvs'           , '' ),
	(123 , 'Rebla GTS'                         , 'rebla'          , 25000  , 'suvs'           , '' ),
	(124 , 'Rocoto'                            , 'rocoto'         , 25000  , 'suvs'           , '' ),
	(125 , 'Seminole'                          , 'seminole'       , 25000  , 'suvs'           , '' ),
	(126 , 'Seminole Frontier'                 , 'seminole2'      , 22500  , 'suvs'           , '' ),
	(127 , 'Serrano'                           , 'serrano'        , 22500  , 'suvs'           , '' ),
	(128 , 'Toros'                             , 'toros'          , 25000  , 'suvs'           , '' ),
	(129 , 'XLS'                               , 'xls'            , 25000  , 'suvs'           , '' ),
	(130 , 'XLS Armored'                       , 'xls2'           , 50000  , 'suvs'           , '' ),
	(150 , 'Cognoscenti Cabrio'                , 'cogcabrio'      , 35000  , 'coupes'         , '' ),
	(151 , 'Exemplar'                          , 'exemplar'       , 35000  , 'coupes'         , '' ),
	(152 , 'F620'                              , 'f620'           , 45000  , 'coupes'         , '' ),
	(153 , 'Felon'                             , 'felon'          , 35000  , 'coupes'         , '' ),
	(154 , 'Felon GT'                          , 'felon2'         , 35000  , 'coupes'         , '' ),
	(155 , 'Jackal'                            , 'jackal'         , 35000  , 'coupes'         , '' ),
	(156 , 'Oracle XS'                         , 'oracle'         , 35000  , 'coupes'         , '' ),
	(157 , 'Oracle'                            , 'oracle2'        , 35000  , 'coupes'         , '' ),
	(158 , 'Sentinel'                          , 'sentinel'       , 35000  , 'coupes'         , '' ),
	(159 , 'Sentinel XS'                       , 'sentinel2'      , 35000  , 'coupes'         , '' ),
	(160 , 'Windsor'                           , 'windsor'        , 50000  , 'coupes'         , '' ),
	(161 , 'Windsor Drop'                      , 'windsor2'       , 50000  , 'coupes'         , '' ),
	(162 , 'Zion'                              , 'zion'           , 35000  , 'coupes'         , '' ),
	(163 , 'Zion Cabrio'                       , 'zion2'          , 35000  , 'coupes'         , '' ),
	(200 , 'Blade'                             , 'blade'          , 15000  , 'muscles'        , '' ),
	(201 , 'Buccaneer'                         , 'buccaneer'      , 15000  , 'muscles'        , '' ),
	(202 , 'Buccaneer Rider'                   , 'buccaneer2'     , 20000  , 'muscles'        , '' ),
	(203 , 'Chino'                             , 'chino'          , 15000  , 'muscles'        , '' ),
	(204 , 'Chino Custom'                      , 'chino2'         , 20000  , 'muscles'        , '' ),
	(205 , 'Clique'                            , 'clique'         , 20000  , 'muscles'        , '' ),
	(206 , 'Coquette BlackFin'                 , 'coquette3'      , 50000  , 'muscles'        , '' ),
	(207 , 'Deviant'                           , 'deviant'        , 30000  , 'muscles'        , '' ),
	(208 , 'Dominator'                         , 'dominator'      , 20000  , 'muscles'        , '' ),
	(209 , 'Dominator Pisswasser'              , 'dominator2'     , 20000  , 'muscles'        , '' ),
	(210 , 'Dominator GTX'                     , 'dominator3'     , 30000  , 'muscles'        , '' ),
	(211 , 'Dukes'                             , 'dukes'          , 15000  , 'muscles'        , '' ),
	(212 , 'Dukes Beater'                      , 'dukes3'         , 15000  , 'muscles'        , '' ),
	(213 , 'Ellie'                             , 'ellie'          , 30000  , 'muscles'        , '' ),
	(214 , 'Faction'                           , 'faction'        , 15000  , 'muscles'        , '' ),
	(215 , 'Faction Custom'                    , 'faction2'       , 20000  , 'muscles'        , '' ),
	(216 , 'Faction Custom Donk'               , 'faction3'       , 20000  , 'muscles'        , '' ),
	(217 , 'Gauntlet'                          , 'gauntlet'       , 20000  , 'muscles'        , '' ),
	(218 , 'Gauntlet Redwood'                  , 'gauntlet2'      , 20000  , 'muscles'        , '' ),
	(219 , 'Gauntlet Classic'                  , 'gauntlet3'      , 20000  , 'muscles'        , '' ),
	(220 , 'Gauntlet Hellfire'                 , 'gauntlet4'      , 30000  , 'muscles'        , '' ),
	(221 , 'Gauntlet Classic Custom'           , 'gauntlet5'      , 20000  , 'muscles'        , '' ),
	(222 , 'Hermes'                            , 'hermes'         , 30000  , 'muscles'        , '' ),
	(223 , 'Hotknife'                          , 'hotknife'       , 30000  , 'muscles'        , '' ),
	(224 , 'Hustler'                           , 'hustler'        , 30000  , 'muscles'        , '' ),
	(225 , 'Impaler'                           , 'impaler'        , 15000  , 'muscles'        , '' ),
	(226 , 'Lurcher'                           , 'lurcher'        , 15000  , 'muscles'        , '' ),
	(227 , 'Manana Custom'                     , 'manana2'        , 15000  , 'muscles'        , '' ),
	(228 , 'Moonbeam'                          , 'moonbeam'       , 15000  , 'muscles'        , '' ),
	(229 , 'Moonbeam Custom'                   , 'moonbeam2'      , 20000  , 'muscles'        , '' ),
	(230 , 'Nightshade'                        , 'nightshade'     , 30000  , 'muscles'        , '' ),
	(231 , 'Peyote Gasser'                     , 'peyote2'        , 30000  , 'muscles'        , '' ),
	(232 , 'Phoenix'                           , 'phoenix'        , 15000  , 'muscles'        , '' ),
	(233 , 'Picador'                           , 'picador'        , 15000  , 'muscles'        , '' ),
	(234 , 'Rat-Loader'                        , 'ratloader'      , 12500  , 'muscles'        , '' ),
	(235 , 'Rat-Truck'                         , 'ratloader2'     , 15000  , 'muscles'        , '' ),
	(236 , 'Ruiner'                            , 'ruiner'         , 15000  , 'muscles'        , '' ),
	(237 , 'Sabre Turbo'                       , 'sabregt'        , 15000  , 'muscles'        , '' ),
	(238 , 'Sabre Turbo Custom'                , 'sabregt2'       , 20000  , 'muscles'        , '' ),
	(239 , 'Slamvan'                           , 'slamvan'        , 15000  , 'muscles'        , '' ),
	(240 , 'Slamvan Lost'                      , 'slamvan2'       , 15000  , 'muscles'        , '' ),
	(241 , 'Slamvan Custom'                    , 'slamvan3'       , 15000  , 'muscles'        , '' ),
	(242 , 'Stallion'                          , 'stalion'        , 15000  , 'muscles'        , '' ),
	(243 , 'Stallion Burger Shot'              , 'stalion2'       , 15000  , 'muscles'        , '' ),
	(244 , 'Tampa'                             , 'tampa'          , 15000  , 'muscles'        , '' ),
	(245 , 'Tulip'                             , 'tulip'          , 15000  , 'muscles'        , '' ),
	(246 , 'Vamos'                             , 'vamos'          , 15000  , 'muscles'        , '' ),
	(247 , 'Vigero'                            , 'vigero'         , 15000  , 'muscles'        , '' ),
	(248 , 'Virgo'                             , 'virgo'          , 15000  , 'muscles'        , '' ),
	(249 , 'Virgo Classic Custom'              , 'virgo2'         , 20000  , 'muscles'        , '' ),
	(250 , 'Virgo Classic'                     , 'virgo3'         , 15000  , 'muscles'        , '' ),
	(251 , 'Voodoo Custom'                     , 'voodoo'         , 20000  , 'muscles'        , '' ),
	(252 , 'Voodoo'                            , 'voodoo2'        , 12500  , 'muscles'        , '' ),
	(253 , 'Yosemite'                          , 'yosemite'       , 15000  , 'muscles'        , '' ),
	(254 , 'Yosemite Drift'                    , 'yosemite2'      , 20000  , 'muscles'        , '' ),
	(260 , 'Roosevelt'                         , 'btype'          , 40000  , 'sportsclassics' , '' ),
	(261 , 'Franken Strange'                   , 'btype3'         , 50000  , 'sportsclassics' , '' ),
	(262 , 'Roosevelt Valor'                   , 'btype2'         , 40000  , 'sportsclassics' , '' ),
	(263 , 'Casco'                             , 'casco'          , 40000  , 'sportsclassics' , '' ),
	(264 , 'Cheburek'                          , 'cheburek'       , 30000  , 'sportsclassics' , '' ),
	(265 , 'Cheetah Classic'                   , 'cheetah2'       , 50000  , 'sportsclassics' , '' ),
	(266 , 'Coquette Classic'                  , 'coquette2'      , 50000  , 'sportsclassics' , '' ),
	(267 , 'Dynasty'                           , 'dynasty'        , 30000  , 'sportsclassics' , '' ),
	(268 , 'Fagaloa'                           , 'fagaloa'        , 30000  , 'sportsclassics' , '' ),
	(269 , 'Stirling GT'                       , 'feltzer3'       , 40000  , 'sportsclassics' , '' ),
	(270 , 'GT 500'                            , 'gt500'          , 40000  , 'sportsclassics' , '' ),
	(271 , 'Infernus Classic'                  , 'infernus2'      , 50000  , 'sportsclassics' , '' ),
	(272 , 'Mamba'                             , 'mamba'          , 40000  , 'sportsclassics' , '' ),
	(273 , 'Manana'                            , 'manana'         , 30000  , 'sportsclassics' , '' ),
	(274 , 'Michelli GT'                       , 'michelli'       , 30000  , 'sportsclassics' , '' ),
	(275 , 'Monroe'                            , 'monroe'         , 40000  , 'sportsclassics' , '' ),
	(276 , 'Nebula Turbo'                      , 'nebula'         , 30000  , 'sportsclassics' , '' ),
	(277 , 'Peyote'                            , 'peyote'         , 30000  , 'sportsclassics' , '' ),
	(278 , 'Peyote Gasser'                     , 'peyote3'        , 35000  , 'sportsclassics' , '' ),
	(279 , 'Pigalle'                           , 'pigalle'        , 30000  , 'sportsclassics' , '' ),
	(280 , 'Rapid GT Classic'                  , 'rapidgt3'       , 35000  , 'sportsclassics' , '' ),
	(281 , 'Retinue'                           , 'retinue'        , 30000  , 'sportsclassics' , '' ),
	(282 , 'Retinue MK II'                     , 'retinue2'       , 35000  , 'sportsclassics' , '' ),
	(283 , 'Savestra'                          , 'savestra'       , 35000  , 'sportsclassics' , '' ),
	(284 , 'Stinger'                           , 'stinger'        , 35000  , 'sportsclassics' , '' ),
	(285 , 'Stinger GT'                        , 'stingergt'      , 40000  , 'sportsclassics' , '' ),
	(286 , 'Swinger'                           , 'swinger'        , 50000  , 'sportsclassics' , '' ),
	(287 , 'Torero'                            , 'torero'         , 50000  , 'sportsclassics' , '' ),
	(288 , 'Tornado'                           , 'tornado'        , 35000  , 'sportsclassics' , '' ),
	(289 , 'Tornado 2'                         , 'tornado2'       , 35000  , 'sportsclassics' , '' ),
	(290 , 'Tornado 3'                         , 'tornado3'       , 30000  , 'sportsclassics' , '' ),
	(291 , 'Tornado 4'                         , 'tornado4'       , 30000  , 'sportsclassics' , '' ),
	(292 , 'Tornado Custom'                    , 'tornado5'       , 35000  , 'sportsclassics' , '' ),
	(293 , 'Tornado Rat Rod'                   , 'tornado6'       , 35000  , 'sportsclassics' , '' ),
	(294 , 'Turismo Classic'                   , 'turismo2'       , 50000  , 'sportsclassics' , '' ),
	(295 , 'Viseris'                           , 'viseris'        , 40000  , 'sportsclassics' , '' ),
	(296 , '190z'                              , 'z190'           , 40000  , 'sportsclassics' , '' ),
	(297 , 'Zion Classic'                      , 'zion3'          , 30000  , 'sportsclassics' , '' ),
	(298 , 'Z-Type'                            , 'ztype'          , 40000  , 'sportsclassics' , '' ),
	(300 , 'Alpha'                             , 'alpha'          , 50000  , 'sports'         , '' ),
	(301 , 'Banshee'                           , 'banshee'        , 75000  , 'sports'         , '' ),
	(302 , 'Bestia GTS'                        , 'bestiagts'      , 50000  , 'sports'         , '' ),
	(303 , 'Blista Compact'                    , 'blista2'        , 25000  , 'sports'         , '' ),
	(304 , 'Blista Go Go Monkey'               , 'blista3'        , 25000  , 'sports'         , '' ),
	(305 , 'Buffalo'                           , 'buffalo'        , 50000  , 'sports'         , '' ),
	(306 , 'Buffalo S'                         , 'buffalo2'       , 50000  , 'sports'         , '' ),
	(307 , 'Buffalo Sprunk'                    , 'buffalo3'       , 50000  , 'sports'         , '' ),
	(308 , 'Carbonizzare'                      , 'carbonizzare'   , 75000  , 'sports'         , '' ),
	(309 , 'Comet'                             , 'comet2'         , 50000  , 'sports'         , '' ),
	(310 , 'Comet Retro Custom'                , 'comet3'         , 52500  , 'sports'         , '' ),
	(311 , 'Comet Safari'                      , 'comet4'         , 50000  , 'sports'         , '' ),
	(312 , 'Comet SR'                          , 'comet5'         , 55000  , 'sports'         , '' ),
	(313 , 'Coquette'                          , 'coquette'       , 75000  , 'sports'         , '' ),
	(314 , 'Coquette D10'                      , 'coquette4'      , 100000 , 'sports'         , '' ),
	(315 , '8F Drafter'                        , 'drafter'        , 50000  , 'sports'         , '' ),
	(316 , 'Elegy Retro Custom'                , 'elegy'          , 50000  , 'sports'         , '' ),
	(317 , 'Elegy RH8'                         , 'elegy2'         , 50000  , 'sports'         , '' ),
	(318 , 'Feltzer'                           , 'feltzer2'       , 50000  , 'sports'         , '' ),
	(319 , 'Flash GT'                          , 'flashgt'        , 50000  , 'sports'         , '' ),
	(320 , 'Furore GT'                         , 'furoregt'       , 50000  , 'sports'         , '' ),
	(321 , 'Fusilade'                          , 'fusilade'       , 50000  , 'sports'         , '' ),
	(322 , 'Futo'                              , 'futo'           , 25000  , 'sports'         , '' ),
	(323 , 'GB200'                             , 'gb200'          , 37500  , 'sports'         , '' ),
	(324 , 'Hotring Sabre'                     , 'hotring'        , 50000  , 'sports'         , '' ),
	(325 , 'Imorgon'                           , 'imorgon'        , 75000  , 'sports'         , '' ),
	(326 , 'Issi Sport'                        , 'issi7'          , 37500  , 'sports'         , '' ),
	(327 , 'Itali GTO'                         , 'italigto'       , 100000 , 'sports'         , '' ),
	(328 , 'Itali RSX'                         , 'italirsx'       , 100000 , 'sports'         , '' ),
	(329 , 'Jester'                            , 'jester'         , 75000  , 'sports'         , '' ),
	(330 , 'Jester (Racecar)'                  , 'jester2'        , 75000  , 'sports'         , '' ),
	(331 , 'Jester Classic'                    , 'jester3'        , 37500  , 'sports'         , '' ),
	(332 , 'Jugular'                           , 'jugular'        , 50000  , 'sports'         , '' ),
	(333 , 'Khamelion'                         , 'khamelion'      , 50000  , 'sports'         , '' ),
	(334 , 'Komoda'                            , 'komoda'         , 50000  , 'sports'         , '' ),
	(335 , 'Kuruma'                            , 'kuruma'         , 50000  , 'sports'         , '' ),
	(336 , 'Locust'                            , 'locust'         , 75000  , 'sports'         , '' ),
	(337 , 'Lynx'                              , 'lynx'           , 50000  , 'sports'         , '' ),
	(338 , 'Massacro'                          , 'massacro'       , 50000  , 'sports'         , '' ),
	(339 , 'Massacro (Racecar)'                , 'massacro2'      , 50000  , 'sports'         , '' ),
	(340 , 'Neo'                               , 'neo'            , 50000  , 'sports'         , '' ),
	(341 , 'Neon'                              , 'neon'           , 50000  , 'sports'         , '' ),
	(342 , '9F'                                , 'ninef'          , 50000  , 'sports'         , '' ),
	(343 , '9F Cabrio'                         , 'ninef2'         , 50000  , 'sports'         , '' ),
	(344 , 'Omnis'                             , 'omnis'          , 37500  , 'sports'         , '' ),
	(345 , 'Paragon R'                         , 'paragon'        , 50000  , 'sports'         , '' ),
	(346 , 'Pariah'                            , 'pariah'         , 50000  , 'sports'         , '' ),
	(347 , 'Penumbra'                          , 'penumbra'       , 37500  , 'sports'         , '' ),
	(348 , 'Penumbra FF'                       , 'penumbra2'      , 37500  , 'sports'         , '' ),
	(349 , 'Raiden'                            , 'raiden'         , 50000  , 'sports'         , '' ),
	(350 , 'Rapid GT'                          , 'rapidgt'        , 50000  , 'sports'         , '' ),
	(351 , 'Rapid GT 2'                        , 'rapidgt2'       , 50000  , 'sports'         , '' ),
	(352 , 'Raptor'                            , 'raptor'         , 37500  , 'sports'         , '' ),
	(353 , 'Revolter'                          , 'revolter'       , 50000  , 'sports'         , '' ),
	(354 , 'Ruston'                            , 'ruston'         , 75000  , 'sports'         , '' ),
	(355 , 'Schafter V12'                      , 'schafter3'      , 25000  , 'sports'         , '' ),
	(356 , 'Schafter LWB'                      , 'schafter4'      , 25000  , 'sports'         , '' ),
	(357 , 'Schlagen GT'                       , 'schlagen'       , 50000  , 'sports'         , '' ),
	(358 , 'Schwartzer'                        , 'schwarzer'      , 37500  , 'sports'         , '' ),
	(359 , 'Sentinel Classic'                  , 'sentinel3'      , 37500  , 'sports'         , '' ),
	(360 , 'Seven 70'                          , 'seven70'        , 50000  , 'sports'         , '' ),
	(361 , 'Specter'                           , 'specter'        , 50000  , 'sports'         , '' ),
	(362 , 'Specter Custom'                    , 'specter2'       , 50000  , 'sports'         , '' ),
	(363 , 'Streiter'                          , 'streiter'       , 50000  , 'sports'         , '' ),
	(364 , 'Sugoi'                             , 'sugoi'          , 50000  , 'sports'         , '' ),
	(365 , 'Sultan'                            , 'sultan'         , 25000  , 'sports'         , '' ),
	(366 , 'Sultan Classic'                    , 'sultan2'        , 37500  , 'sports'         , '' ),
	(367 , 'Surano'                            , 'surano'         , 50000  , 'sports'         , '' ),
	(368 , 'Drift Tampa'                       , 'tampa2'         , 75000  , 'sports'         , '' ),
	(369 , 'Tropos Rallye'                     , 'tropos'         , 50000  , 'sports'         , '' ),
	(370 , 'Verlierer'                         , 'verlierer2'     , 75000  , 'sports'         , '' ),
	(371 , 'V-STR'                             , 'vstr'           , 50000  , 'sports'         , '' ),
	(400 , 'Adder'                             , 'adder'          , 250000 , 'supers'         , '' ),
	(401 , 'Autarch'                           , 'autarch'        , 375000 , 'supers'         , '' ),
	(402 , 'Banshee 900R'                      , 'banshee2'       , 250000 , 'supers'         , '' ),
	(403 , 'Bullet'                            , 'bullet'         , 250000 , 'supers'         , '' ),
	(404 , 'Cheetah'                           , 'cheetah'        , 250000 , 'supers'         , '' ),
	(405 , 'Cyclone'                           , 'cyclone'        , 250000 , 'supers'         , '' ),
	(406 , 'Deveste Eight'                     , 'deveste'        , 375000 , 'supers'         , '' ),
	(407 , 'Emerus'                            , 'emerus'         , 375000 , 'supers'         , '' ),
	(408 , 'Entity XF'                         , 'entityxf'       , 250000 , 'supers'         , '' ),
	(409 , 'Entity XXR'                        , 'entity2'        , 300000 , 'supers'         , '' ),
	(410 , 'FMJ'                               , 'fmj'            , 375000 , 'supers'         , '' ),
	(411 , 'PR4'                               , 'formula'        , 500000 , 'supers'         , '' ),
	(412 , 'R88'                               , 'formula2'       , 500000 , 'supers'         , '' ),
	(413 , 'Furia'                             , 'furia'          , 300000 , 'supers'         , '' ),
	(414 , 'GP1'                               , 'gp1'            , 375000 , 'supers'         , '' ),
	(415 , 'Infernus'                          , 'infernus'       , 250000 , 'supers'         , '' ),
	(416 , 'Itali GTB'                         , 'italigtb'       , 375000 , 'supers'         , '' ),
	(417 , 'Itali GTB Custom'                  , 'italigtb2'      , 375000 , 'supers'         , '' ),
	(418 , 'Krieger'                           , 'krieger'        , 375000 , 'supers'         , '' ),
	(419 , 'RE-7B'                             , 'le7b'           , 375000 , 'supers'         , '' ),
	(420 , 'Nero'                              , 'nero'           , 300000 , 'supers'         , '' ),
	(421 , 'Nero Custom'                       , 'nero2'          , 300000 , 'supers'         , '' ),
	(422 , 'BR8'                               , 'openwheel1'     , 500000 , 'supers'         , '' ),
	(423 , 'DR1'                               , 'openwheel2'     , 500000 , 'supers'         , '' ),
	(424 , 'Osiris'                            , 'osiris'         , 300000 , 'supers'         , '' ),
	(425 , 'Penetrator'                        , 'penetrator'     , 250000 , 'supers'         , '' ),
	(426 , 'Pfister 811'                       , 'pfister811'     , 300000 , 'supers'         , '' ),
	(427 , 'X80 Proto'                         , 'prototipo'      , 375000 , 'supers'         , '' ),
	(428 , 'Reaper'                            , 'reaper'         , 375000 , 'supers'         , '' ),
	(429 , 'S80RR'                             , 's80'            , 375000 , 'supers'         , '' ),
	(430 , 'SC1'                               , 'sc1'            , 300000 , 'supers'         , '' ),
	(431 , 'ETR1'                              , 'sheava'         , 250000 , 'supers'         , '' ),
	(432 , 'Sultan RS'                         , 'sultanrs'       , 250000 , 'supers'         , '' ),
	(433 , 'T20'                               , 't20'            , 300000 , 'supers'         , '' ),
	(434 , 'Taipan'                            , 'taipan'         , 375000 , 'supers'         , '' ),
	(435 , 'Tempesta'                          , 'tempesta'       , 375000 , 'supers'         , '' ),
	(436 , 'Tezeract'                          , 'tezeract'       , 375000 , 'supers'         , '' ),
	(437 , 'Tigon'                             , 'tigon'          , 375000 , 'supers'         , '' ),
	(438 , 'Thrax'                             , 'thrax'          , 375000 , 'supers'         , '' ),
	(439 , 'Turismo R'                         , 'turismor'       , 375000 , 'supers'         , '' ),
	(440 , 'Tyrant'                            , 'tyrant'         , 300000 , 'supers'         , '' ),
	(441 , 'Tyrus'                             , 'tyrus'          , 375000 , 'supers'         , '' ),
	(442 , 'Vacca'                             , 'vacca'          , 300000 , 'supers'         , '' ),
	(443 , 'Vagner'                            , 'vagner'         , 375000 , 'supers'         , '' ),
	(444 , 'Visione'                           , 'visione'        , 375000 , 'supers'         , '' ),
	(445 , 'Voltic'                            , 'voltic'         , 250000 , 'supers'         , '' ),
	(446 , 'XA-21'                             , 'xa21'           , 375000 , 'supers'         , '' ),
	(447 , 'Zentorno'                          , 'zentorno'       , 375000 , 'supers'         , '' ),
	(448 , 'Zorrusso'                          , 'zorrusso'       , 375000 , 'supers'         , '' ),
	(500 , 'Akuma'                             , 'akuma'          , 10000  , 'motorcycles'    , '' ),
	(501 , 'Avarus'                            , 'avarus'         , 20000  , 'motorcycles'    , '' ),
	(502 , 'Bagger'                            , 'bagger'         , 20000  , 'motorcycles'    , '' ),
	(503 , 'Bati 801'                          , 'bati'           , 15000  , 'motorcycles'    , '' ),
	(504 , 'Bati 801RR'                        , 'bati2'          , 15000  , 'motorcycles'    , '' ),
	(505 , 'BF400'                             , 'bf400'          , 7500   , 'motorcycles'    , '' ),
	(506 , 'Blazer'                            , 'blazer'         , 10000  , 'motorcycles'    , '' ),
	(507 , 'Blazer Hot Rod'                    , 'blazer3'        , 10000  , 'motorcycles'    , '' ),
	(508 , 'Blazer Sport'                      , 'blazer4'        , 10000  , 'motorcycles'    , '' ),
	(509 , 'Caddy'                             , 'caddy'          , 5000   , 'motorcycles'    , '' ),
	(510 , 'Caddy 2'                           , 'caddy2'         , 5000   , 'motorcycles'    , '' ),
	(511 , 'Caddy 3'                           , 'caddy3'         , 5000   , 'motorcycles'    , '' ),
	(512 , 'Carbon RS'                         , 'carbonrs'       , 15000  , 'motorcycles'    , '' ),
	(513 , 'Chimera'                           , 'chimera'        , 20000  , 'motorcycles'    , '' ),
	(514 , 'Cliffhanger'                       , 'cliffhanger'    , 7500   , 'motorcycles'    , '' ),
	(515 , 'Daemon'                            , 'daemon'         , 10000  , 'motorcycles'    , '' ),
	(516 , 'Daemon 2'                          , 'daemon2'        , 10000  , 'motorcycles'    , '' ),
	(517 , 'Defiler'                           , 'defiler'        , 10000  , 'motorcycles'    , '' ),
	(518 , 'Diabolus'                          , 'diablous'       , 15000  , 'motorcycles'    , '' ),
	(519 , 'Diabolus Custom'                   , 'diablous2'      , 15000  , 'motorcycles'    , '' ),
	(520 , 'Double T'                          , 'double'         , 15000  , 'motorcycles'    , '' ),
	(521 , 'Enduro'                            , 'enduro'         , 7500   , 'motorcycles'    , '' ),
	(522 , 'Esskey'                            , 'esskey'         , 7500   , 'motorcycles'    , '' ),
	(523 , 'Faggio Sport'                      , 'faggio'         , 2500   , 'motorcycles'    , '' ),
	(524 , 'Faggio'                            , 'faggio2'        , 2500   , 'motorcycles'    , '' ),
	(525 , 'Faggio Mod'                        , 'faggio3'        , 2500   , 'motorcycles'    , '' ),
	(526 , 'FCR 1000'                          , 'fcr'            , 10000  , 'motorcycles'    , '' ),
	(527 , 'FCR 1000 Custom'                   , 'fcr2'           , 10000  , 'motorcycles'    , '' ),
	(528 , 'Gargoyle'                          , 'gargoyle'       , 15000  , 'motorcycles'    , '' ),
	(529 , 'Hakuchou'                          , 'hakuchou'       , 15000  , 'motorcycles'    , '' ),
	(530 , 'Hakuchou Sport'                    , 'hakuchou2'      , 20000  , 'motorcycles'    , '' ),
	(531 , 'Hexer'                             , 'hexer'          , 20000  , 'motorcycles'    , '' ),
	(532 , 'Innovation'                        , 'innovation'     , 20000  , 'motorcycles'    , '' ),
	(533 , 'Lectro'                            , 'lectro'         , 15000  , 'motorcycles'    , '' ),
	(534 , 'Manchez'                           , 'manchez'        , 10000  , 'motorcycles'    , '' ),
	(535 , 'Manchez 2'                         , 'manchez2'       , 10000  , 'motorcycles'    , '' ),
	(536 , 'Nemesis'                           , 'nemesis'        , 10000  , 'motorcycles'    , '' ),
	(537 , 'Nightblade'                        , 'nightblade'     , 20000  , 'motorcycles'    , '' ),
	(538 , 'PCJ 600'                           , 'pcj'            , 10000  , 'motorcycles'    , '' ),
	(539 , 'Rat Bike'                          , 'ratbike'        , 20000  , 'motorcycles'    , '' ),
	(540 , 'Ruffian'                           , 'ruffian'        , 10000  , 'motorcycles'    , '' ),
	(541 , 'Sanchez'                           , 'sanchez'        , 10000  , 'motorcycles'    , '' ),
	(542 , 'Sanchez Sport'                     , 'sanchez2'       , 10000  , 'motorcycles'    , '' ),
	(543 , 'Sanctus'                           , 'sanctus'        , 20000  , 'motorcycles'    , '' ),
	(544 , 'Stryder'                           , 'stryder'        , 20000  , 'motorcycles'    , '' ),
	(545 , 'Sovereign'                         , 'sovereign'      , 20000  , 'motorcycles'    , '' ),
	(546 , 'Thrust'                            , 'thrust'         , 20000  , 'motorcycles'    , '' ),
	(547 , 'Vader'                             , 'vader'          , 10000  , 'motorcycles'    , '' ),
	(548 , 'Veto Classic'                      , 'veto'           , 5000   , 'motorcycles'    , '' ),
	(549 , 'Veto Modern'                       , 'veto2'          , 5000   , 'motorcycles'    , '' ),
	(550 , 'Vindicator'                        , 'vindicator'     , 20000  , 'motorcycles'    , '' ),
	(551 , 'Vortex'                            , 'vortex'         , 10000  , 'motorcycles'    , '' ),
	(552 , 'Woflsbane'                         , 'wolfsbane'      , 10000  , 'motorcycles'    , '' ),
	(553 , 'Zombie Bobber'                     , 'zombiea'        , 10000  , 'motorcycles'    , '' ),
	(554 , 'Zombie Chopper'                    , 'zombieb'        , 10000  , 'motorcycles'    , '' ),
	(555 , 'Shotaro'                           , 'shotaro'        , 30000  , 'motorcycles'    , '' ),
	(600 , 'Bf Injection'                      , 'bfinjection'    , 15000  , 'offroads'       , '' ),
	(601 , 'Bifta'                             , 'bifta'          , 15000  , 'offroads'       , '' ),
	(602 , 'Bison'                             , 'bison'          , 25000  , 'offroads'       , '' ),
	(603 , 'Bison 3'                           , 'bison3'         , 25000  , 'offroads'       , '' ),
	(604 , 'Bobcat XL'                         , 'bobcatxl'       , 25000  , 'offroads'       , '' ),
	(605 , 'Bodhi'                             , 'bodhi2'         , 15000  , 'offroads'       , '' ),
	(606 , 'Brawler'                           , 'brawler'        , 45000  , 'offroads'       , '' ),
	(607 , 'Caracara 4x4'                      , 'caracara2'      , 50000  , 'offroads'       , '' ),
	(608 , 'Contender'                         , 'contender'      , 45000  , 'offroads'       , '' ),
	(609 , 'Duneloader'                        , 'dloader'        , 25000  , 'offroads'       , '' ),
	(610 , 'Dubsta 6x6'                        , 'dubsta3'        , 50000  , 'offroads'       , '' ),
	(611 , 'Dune Buggy'                        , 'dune'           , 10000  , 'offroads'       , '' ),
	(612 , 'Space Docker'                      , 'dune2'          , 10000  , 'offroads'       , '' ),
	(613 , 'Everon'                            , 'everon'         , 50000  , 'offroads'       , '' ),
	(614 , 'Freecrawler'                       , 'freecrawler'    , 25000  , 'offroads'       , '' ),
	(615 , 'Guardian'                          , 'guardian'       , 50000  , 'offroads'       , '' ),
	(616 , 'Hellion'                           , 'hellion'        , 25000  , 'offroads'       , '' ),
	(617 , 'Insurgent'                         , 'insurgent2'     , 75000  , 'offroads'       , '' ),
	(618 , 'Kalahari'                          , 'kalahari'       , 20000  , 'offroads'       , '' ),
	(619 , 'Kamacho'                           , 'kamacho'        , 50000  , 'offroads'       , '' ),
	(620 , 'Marshall'                          , 'marshall'       , 210000 , 'offroads'       , '' ),
	(621 , 'Mesa Trail'                        , 'mesa3'          , 50000  , 'offroads'       , '' ),
	(622 , 'Liberator'                         , 'monster'        , 210000 , 'offroads'       , '' ),
	(623 , 'Outlaw'                            , 'outlaw'         , 15000  , 'offroads'       , '' ),
	(624 , 'Rancher XL'                        , 'rancherxl'      , 25000  , 'offroads'       , '' ),
	(625 , 'Rusty Rebel'                       , 'rebel'          , 15000  , 'offroads'       , '' ),
	(626 , 'Rebel'                             , 'rebel2'         , 25000  , 'offroads'       , '' ),
	(627 , 'Riata'                             , 'riata'          , 50000  , 'offroads'       , '' ),
	(628 , 'Sadler'                            , 'sadler'         , 25000  , 'offroads'       , '' ),
	(629 , 'Sandking XL'                       , 'sandking'       , 50000  , 'offroads'       , '' ),
	(630 , 'Sandking SWB'                      , 'sandking2'      , 50000  , 'offroads'       , '' ),
	(631 , 'Squaddie'                          , 'squaddie'       , 75000  , 'offroads'       , '' ),
	(632 , 'Trophy Truck'                      , 'trophytruck'    , 75000  , 'offroads'       , '' ),
	(633 , 'Desert Raid'                       , 'trophytruck2'   , 75000  , 'offroads'       , '' ),
	(634 , 'Vagrant'                           , 'vagrant'        , 25000  , 'offroads'       , '' ),
	(635 , 'Verus'                             , 'verus'          , 10000  , 'offroads'       , '' ),
	(636 , 'Vetir'                             , 'vetir'          , 75000  , 'offroads'       , '' ),
	(637 , 'Winky'                             , 'winky'          , 25000  , 'offroads'       , '' ),
	(638 , 'Yosemite Rancher'                  , 'yosemite3'      , 25000  , 'offroads'       , '' ),
	(639 , 'Zhaba'                             , 'zhaba'          , 75000  , 'offroads'       , '' ),
	(650 , 'Burrito'                           , 'burrito3'       , 20000  , 'vans'           , '' ),
	(651 , 'Camper'                            , 'camper'         , 25000  , 'vans'           , '' ),
	(652 , 'Gang Burrito'                      , 'gburrito'       , 20000  , 'vans'           , '' ),
	(653 , 'Gang Burrito 2'                    , 'gburrito2'      , 20000  , 'vans'           , '' ),
	(654 , 'Journey'                           , 'journey'        , 10000  , 'vans'           , '' ),
	(655 , 'Minivan'                           , 'minivan'        , 15000  , 'vans'           , '' ),
	(656 , 'Minivan Custom'                    , 'minivan2'       , 20000  , 'vans'           , '' ),
	(657 , 'Paradise'                          , 'paradise'       , 20000  , 'vans'           , '' ),
	(658 , 'Rumpo Trail'                       , 'rumpo3'         , 25000  , 'vans'           , '' ),
	(659 , 'Speedo'                            , 'speedo'         , 20000  , 'vans'           , '' ),
	(660 , 'Surfer'                            , 'surfer'         , 20000  , 'vans'           , '' ),
	(661 , 'Surfer 2'                          , 'surfer2'        , 10000  , 'vans'           , '' ),
	(662 , 'Youga'                             , 'youga'          , 20000  , 'vans'           , '' ),
	(663 , 'Youga Classic'                     , 'youga2'         , 20000  , 'vans'           , '' ),
	(664 , 'Youga Classic 4x4'                 , 'youga3'         , 25000  , 'vans'           , '' ),
	(685 , 'BMX'                               , 'bmx'            , 150    , 'cycles'         , '' ),
	(686 , 'Cruiser'                           , 'cruiser'        , 200    , 'cycles'         , '' ),
	(687 , 'Fixter'                            , 'fixter'         , 200    , 'cycles'         , '' ),
	(688 , 'Scorcher'                          , 'scorcher'       , 350    , 'cycles'         , '' ),
	(689 , 'Race bike Whippet'                 , 'tribike'        , 500    , 'cycles'         , '' ),
	(690 , 'Race bike Endurex'                 , 'tribike2'       , 500    , 'cycles'         , '' ),
	(691 , 'Race bike Tri-Cycles'              , 'tribike3'       , 500    , 'cycles'         , '' )