Citizen.CreateThread(function()
AddTextEntry("SUBARU", "Subaru")
AddTextEntry("brz13", "BRZ '13")
AddTextEntry("GREDDY", "Greddy")
AddTextEntry("INGS", "Ings")
AddTextEntry("GARGE", "Garge Vary")
AddTextEntry("DELETES", "Spoiler Delete")
AddTextEntry("NOHOOD", "No Hood")
AddTextEntry("CWEST", "C-West")
AddTextEntry("RBKIT", "Rocket Bunny")
AddTextEntry("RACEWING", "Race Wing")
AddTextEntry("RMAGIC", "R-Magic")
end)