USE `es_extended`;

ALTER TABLE `users`
	MODIFY COLUMN `firstname` VARCHAR(16) NULL DEFAULT NULL,
	MODIFY COLUMN `lastname` VARCHAR(16) NULL DEFAULT NULL,
	MODIFY COLUMN `dateofbirth` VARCHAR(10) NULL DEFAULT NULL,
	MODIFY COLUMN `sex` VARCHAR(1) NULL DEFAULT NULL,
	MODIFY COLUMN `height` INT NULL DEFAULT NULL
;
